FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml README.md ./
COPY apps ./apps
COPY configs ./configs
COPY packages ./packages
COPY scripts ./scripts
COPY tests ./tests

RUN pip install --no-cache-dir ".[dev]"

CMD ["python", "-m", "pytest"]
